/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author lahir
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        welcomeImagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userSelectionPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        usernametxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        themePanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        financePanel = new javax.swing.JPanel();
        financeImage = new javax.swing.JLabel();
        financeLabel = new javax.swing.JLabel();
        finishedProductsPanel = new javax.swing.JPanel();
        finishedProductsLabel = new javax.swing.JLabel();
        finishedProductsImage = new javax.swing.JLabel();
        stockMaterialsPanel = new javax.swing.JPanel();
        stockMaterialsLabel = new javax.swing.JLabel();
        stockMaterialsImage = new javax.swing.JLabel();
        qaPanel = new javax.swing.JPanel();
        qaLabel = new javax.swing.JLabel();
        qaImage = new javax.swing.JLabel();
        salesPanel = new javax.swing.JPanel();
        salesLabel = new javax.swing.JLabel();
        salesImage = new javax.swing.JLabel();
        transportsPanel = new javax.swing.JPanel();
        transportsLabel = new javax.swing.JLabel();
        transportsImage = new javax.swing.JLabel();
        returnsPanel = new javax.swing.JPanel();
        returnsLabel = new javax.swing.JLabel();
        returnsImage = new javax.swing.JLabel();
        hrPanel = new javax.swing.JPanel();
        hrLabel = new javax.swing.JLabel();
        hrImage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        themeImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bg.setLayout(new java.awt.CardLayout());

        welcomeImagePanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Welcome.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        welcomeImagePanel.add(jLabel1, gridBagConstraints);

        bg.add(welcomeImagePanel, "card2");

        userSelectionPanel.setBackground(new java.awt.Color(76, 77, 78));
        userSelectionPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("NEOTERIC", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("USER");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 763, 449, 0);
        userSelectionPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("NEOTERIC", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("ADMINISTRATOR");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 50, 449, 0);
        userSelectionPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("NEOTERIC", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("OWNER");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 70, 449, 0);
        userSelectionPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin iconNew.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(460, 50, 0, 0);
        userSelectionPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userIconNew.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(460, 726, 0, 0);
        userSelectionPanel.add(jLabel6, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Owner iconNew.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(460, 44, 0, 733);
        userSelectionPanel.add(jLabel7, gridBagConstraints);

        bg.add(userSelectionPanel, "card3");

        loginPanel.setBackground(new java.awt.Color(76, 77, 78));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Sign In");
        jButton1.setBorder(null);
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jButton1.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 50, 0, 0);
        loginPanel.add(jButton1, gridBagConstraints);

        usernametxt.setBackground(new java.awt.Color(76, 77, 78));
        usernametxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(204, 204, 204));
        usernametxt.setBorder(null);
        usernametxt.setPreferredSize(new java.awt.Dimension(23, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 282;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 0, 1047);
        loginPanel.add(usernametxt, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Clear");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 96;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 50, 580, 0);
        loginPanel.add(jButton2, gridBagConstraints);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ITPFirstInterfaceSmall.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(117, 92, 0, 0);
        loginPanel.add(jLabel8, gridBagConstraints);

        passwordtxt.setBackground(new java.awt.Color(76, 77, 78));
        passwordtxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordtxt.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 236;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 0, 0);
        loginPanel.add(passwordtxt, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(117, 50, 0, 0);
        loginPanel.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 50, 0, 0);
        loginPanel.add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 50, 0, 0);
        loginPanel.add(jSeparator3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 50, 0, 0);
        loginPanel.add(jSeparator4, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 6, 580, 0);
        loginPanel.add(jButton3, gridBagConstraints);

        bg.add(loginPanel, "card4");

        themePanel.setBackground(new java.awt.Color(76, 77, 78));
        themePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        financePanel.setBackground(new java.awt.Color(85, 65, 118));
        financePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                financePanelMousePressed(evt);
            }
        });

        financeImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        financeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Accounting_50px.png"))); // NOI18N

        financeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        financeLabel.setForeground(new java.awt.Color(204, 204, 204));
        financeLabel.setText("Finance Department");
        financeLabel.setName(""); // NOI18N
        financeLabel.setPreferredSize(new java.awt.Dimension(71, 20));

        javax.swing.GroupLayout financePanelLayout = new javax.swing.GroupLayout(financePanel);
        financePanel.setLayout(financePanelLayout);
        financePanelLayout.setHorizontalGroup(
            financePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financePanelLayout.createSequentialGroup()
                .addComponent(financeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(financeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        financePanelLayout.setVerticalGroup(
            financePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(financeImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(financeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.add(financePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        finishedProductsPanel.setBackground(new java.awt.Color(85, 65, 118));
        finishedProductsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                finishedProductsPanelMousePressed(evt);
            }
        });

        finishedProductsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finishedProductsLabel.setForeground(new java.awt.Color(204, 204, 204));
        finishedProductsLabel.setText("Finished Products");

        finishedProductsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Shopping_Cart_50px.png"))); // NOI18N
        finishedProductsImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout finishedProductsPanelLayout = new javax.swing.GroupLayout(finishedProductsPanel);
        finishedProductsPanel.setLayout(finishedProductsPanelLayout);
        finishedProductsPanelLayout.setHorizontalGroup(
            finishedProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishedProductsPanelLayout.createSequentialGroup()
                .addComponent(finishedProductsImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishedProductsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        finishedProductsPanelLayout.setVerticalGroup(
            finishedProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finishedProductsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(finishedProductsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(finishedProductsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 267, -1));

        stockMaterialsPanel.setBackground(new java.awt.Color(85, 65, 118));
        stockMaterialsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockMaterialsPanelMousePressed(evt);
            }
        });

        stockMaterialsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockMaterialsLabel.setForeground(new java.awt.Color(204, 204, 204));
        stockMaterialsLabel.setText("Stock Materials");

        stockMaterialsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Box_50px.png"))); // NOI18N
        stockMaterialsImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout stockMaterialsPanelLayout = new javax.swing.GroupLayout(stockMaterialsPanel);
        stockMaterialsPanel.setLayout(stockMaterialsPanelLayout);
        stockMaterialsPanelLayout.setHorizontalGroup(
            stockMaterialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockMaterialsPanelLayout.createSequentialGroup()
                .addComponent(stockMaterialsImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockMaterialsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        stockMaterialsPanelLayout.setVerticalGroup(
            stockMaterialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockMaterialsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stockMaterialsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(stockMaterialsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 267, -1));

        qaPanel.setBackground(new java.awt.Color(85, 65, 118));
        qaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                qaPanelMousePressed(evt);
            }
        });

        qaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qaLabel.setForeground(new java.awt.Color(204, 204, 204));
        qaLabel.setText("Quality Assurance ");

        qaImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Good_Quality_50px.png"))); // NOI18N
        qaImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout qaPanelLayout = new javax.swing.GroupLayout(qaPanel);
        qaPanel.setLayout(qaPanelLayout);
        qaPanelLayout.setHorizontalGroup(
            qaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qaPanelLayout.createSequentialGroup()
                .addComponent(qaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        qaPanelLayout.setVerticalGroup(
            qaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(qaImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(qaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 267, -1));

        salesPanel.setBackground(new java.awt.Color(85, 65, 118));
        salesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salesPanelMousePressed(evt);
            }
        });

        salesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salesLabel.setForeground(new java.awt.Color(204, 204, 204));
        salesLabel.setText("Sales & Marketing");

        salesImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Advertising_50px.png"))); // NOI18N
        salesImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout salesPanelLayout = new javax.swing.GroupLayout(salesPanel);
        salesPanel.setLayout(salesPanelLayout);
        salesPanelLayout.setHorizontalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addComponent(salesImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        salesPanelLayout.setVerticalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(salesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 267, -1));

        transportsPanel.setBackground(new java.awt.Color(85, 65, 118));
        transportsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transportsPanelMousePressed(evt);
            }
        });

        transportsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transportsLabel.setForeground(new java.awt.Color(204, 204, 204));
        transportsLabel.setText("Transports");

        transportsImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transportsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Interstate_Truck_50px.png"))); // NOI18N
        transportsImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout transportsPanelLayout = new javax.swing.GroupLayout(transportsPanel);
        transportsPanel.setLayout(transportsPanelLayout);
        transportsPanelLayout.setHorizontalGroup(
            transportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportsPanelLayout.createSequentialGroup()
                .addComponent(transportsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transportsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        transportsPanelLayout.setVerticalGroup(
            transportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transportsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transportsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(transportsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 267, -1));

        returnsPanel.setBackground(new java.awt.Color(85, 65, 118));
        returnsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnsPanelMousePressed(evt);
            }
        });

        returnsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnsLabel.setForeground(new java.awt.Color(204, 204, 204));
        returnsLabel.setText("Return Stock");

        returnsImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Return_50px.png"))); // NOI18N
        returnsImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout returnsPanelLayout = new javax.swing.GroupLayout(returnsPanel);
        returnsPanel.setLayout(returnsPanelLayout);
        returnsPanelLayout.setHorizontalGroup(
            returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnsPanelLayout.createSequentialGroup()
                .addComponent(returnsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        returnsPanelLayout.setVerticalGroup(
            returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(returnsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(returnsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 267, -1));

        hrPanel.setBackground(new java.awt.Color(85, 65, 118));
        hrPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hrPanelMousePressed(evt);
            }
        });

        hrLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hrLabel.setForeground(new java.awt.Color(204, 204, 204));
        hrLabel.setText("HR");

        hrImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hrImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Management_50px_2.png"))); // NOI18N
        hrImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout hrPanelLayout = new javax.swing.GroupLayout(hrPanel);
        hrPanel.setLayout(hrPanelLayout);
        hrPanelLayout.setHorizontalGroup(
            hrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrPanelLayout.createSequentialGroup()
                .addComponent(hrImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        hrPanelLayout.setVerticalGroup(
            hrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hrImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(hrPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 267, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Log out");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        sidePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1037, -1, -1));

        themePanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 266, 1080));

        themeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FirstInterface.jpg"))); // NOI18N
        themePanel.add(themeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1650, 1080));

        bg.add(themePanel, "card5");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(bg, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        loginPanel.setVisible(true);
        userSelectionPanel.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        loginPanel.setVisible(true);
        userSelectionPanel.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        loginPanel.setVisible(true);
        userSelectionPanel.setVisible(false);

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        loginPanel.setVisible(true);
        userSelectionPanel.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        loginPanel.setVisible(true);
        userSelectionPanel.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        loginPanel.setVisible(true);
        userSelectionPanel.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        themePanel.setVisible(true);
        loginPanel.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        usernametxt.setText("");
        passwordtxt.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        userSelectionPanel.setVisible(true);
        loginPanel.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void financePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financePanelMousePressed
        setColor(financePanel);
        resetColor(stockMaterialsPanel);
        resetColor(salesPanel);
        resetColor(transportsPanel);
        resetColor(returnsPanel);
        resetColor(finishedProductsPanel);
        resetColor(hrPanel);
        resetColor(qaPanel);
    }//GEN-LAST:event_financePanelMousePressed

    private void finishedProductsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishedProductsPanelMousePressed
        setColor(finishedProductsPanel);
        resetColor(stockMaterialsPanel);
        resetColor(salesPanel);
        resetColor(transportsPanel);
        resetColor(returnsPanel);
        resetColor(financePanel);
        resetColor(hrPanel);
        resetColor(qaPanel);
    }//GEN-LAST:event_finishedProductsPanelMousePressed

    private void stockMaterialsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMaterialsPanelMousePressed
        setColor(stockMaterialsPanel);
        resetColor(finishedProductsPanel);
        resetColor(salesPanel);
        resetColor(transportsPanel);
        resetColor(returnsPanel);
        resetColor(financePanel);
        resetColor(hrPanel);
        resetColor(qaPanel);
    }//GEN-LAST:event_stockMaterialsPanelMousePressed

    private void qaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qaPanelMousePressed
        setColor(qaPanel);
        resetColor(stockMaterialsPanel);
        resetColor(salesPanel);
        resetColor(transportsPanel);
        resetColor(returnsPanel);
        resetColor(financePanel);
        resetColor(hrPanel);
        resetColor(finishedProductsPanel);
    }//GEN-LAST:event_qaPanelMousePressed

    private void salesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesPanelMousePressed
        setColor(salesPanel);
        resetColor(stockMaterialsPanel);
        resetColor(finishedProductsPanel);
        resetColor(transportsPanel);
        resetColor(returnsPanel);
        resetColor(financePanel);
        resetColor(hrPanel);
        resetColor(qaPanel);
    }//GEN-LAST:event_salesPanelMousePressed

    private void transportsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transportsPanelMousePressed
        setColor(transportsPanel);
        resetColor(stockMaterialsPanel);
        resetColor(salesPanel);
        resetColor(finishedProductsPanel);
        resetColor(returnsPanel);
        resetColor(financePanel);
        resetColor(hrPanel);
        resetColor(qaPanel);
    }//GEN-LAST:event_transportsPanelMousePressed

    private void returnsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsPanelMousePressed
        setColor(returnsPanel);
        resetColor(stockMaterialsPanel);
        resetColor(salesPanel);
        resetColor(transportsPanel);
        resetColor(finishedProductsPanel);
        resetColor(financePanel);
        resetColor(hrPanel);
        resetColor(qaPanel);
    }//GEN-LAST:event_returnsPanelMousePressed

    private void hrPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrPanelMousePressed
        setColor(hrPanel);
        resetColor(stockMaterialsPanel);
        resetColor(salesPanel);
        resetColor(transportsPanel);
        resetColor(returnsPanel);
        resetColor(financePanel);
        resetColor(finishedProductsPanel);
        resetColor(qaPanel);
    }//GEN-LAST:event_hrPanelMousePressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        loginPanel.setVisible(true);
        themePanel.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        userSelectionPanel.setVisible(true);
        welcomeImagePanel.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

     public void setColor(JPanel panel)
    {
        panel.setBackground(new Color(54,33,89));
    }
    
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel financeImage;
    private javax.swing.JLabel financeLabel;
    private javax.swing.JPanel financePanel;
    private javax.swing.JLabel finishedProductsImage;
    private javax.swing.JLabel finishedProductsLabel;
    private javax.swing.JPanel finishedProductsPanel;
    private javax.swing.JLabel hrImage;
    private javax.swing.JLabel hrLabel;
    private javax.swing.JPanel hrPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JLabel qaImage;
    private javax.swing.JLabel qaLabel;
    private javax.swing.JPanel qaPanel;
    private javax.swing.JLabel returnsImage;
    private javax.swing.JLabel returnsLabel;
    private javax.swing.JPanel returnsPanel;
    private javax.swing.JLabel salesImage;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel stockMaterialsImage;
    private javax.swing.JLabel stockMaterialsLabel;
    private javax.swing.JPanel stockMaterialsPanel;
    private javax.swing.JLabel themeImage;
    private javax.swing.JPanel themePanel;
    private javax.swing.JLabel transportsImage;
    private javax.swing.JLabel transportsLabel;
    private javax.swing.JPanel transportsPanel;
    private javax.swing.JPanel userSelectionPanel;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JPanel welcomeImagePanel;
    // End of variables declaration//GEN-END:variables
}
