/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Internal.DeliveryMain;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

///ghhjghjghj

/**
 *
 * @author lahir
 */
public class Theme extends javax.swing.JFrame {

    /**
     * Creates new form Theme
     */
    public Theme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        stockPanel = new javax.swing.JPanel();
        stockLabel = new javax.swing.JLabel();
        stockImage = new javax.swing.JLabel();
        productionPanel = new javax.swing.JPanel();
        productionLabel = new javax.swing.JLabel();
        productionImage = new javax.swing.JLabel();
        financePanel = new javax.swing.JPanel();
        financeLabel = new javax.swing.JLabel();
        financeImage = new javax.swing.JLabel();
        salesPanel = new javax.swing.JPanel();
        salesLabel = new javax.swing.JLabel();
        salesImage = new javax.swing.JLabel();
        hrPanel = new javax.swing.JPanel();
        hrLabel = new javax.swing.JLabel();
        hrImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        salesDesktopPane = new javax.swing.JDesktopPane();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(76, 77, 78));

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));

        stockPanel.setBackground(new java.awt.Color(85, 65, 118));
        stockPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockPanelMousePressed(evt);
            }
        });

        stockLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockLabel.setForeground(new java.awt.Color(204, 204, 204));
        stockLabel.setText("Stock Management");

        stockImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Shopping_Cart_50px.png"))); // NOI18N
        stockImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addComponent(stockImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stockImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        productionPanel.setBackground(new java.awt.Color(85, 65, 118));
        productionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productionPanelMousePressed(evt);
            }
        });

        productionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productionLabel.setForeground(new java.awt.Color(204, 204, 204));
        productionLabel.setText("Production Management");

        productionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Good_Quality_50px.png"))); // NOI18N
        productionImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout productionPanelLayout = new javax.swing.GroupLayout(productionPanel);
        productionPanel.setLayout(productionPanelLayout);
        productionPanelLayout.setHorizontalGroup(
            productionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productionPanelLayout.createSequentialGroup()
                .addComponent(productionImage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        productionPanelLayout.setVerticalGroup(
            productionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productionImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        financePanel.setBackground(new java.awt.Color(85, 65, 118));
        financePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                financePanelMousePressed(evt);
            }
        });

        financeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        financeLabel.setForeground(new java.awt.Color(204, 204, 204));
        financeLabel.setText("Finance Management");

        financeImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        financeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Advertising_50px.png"))); // NOI18N
        financeImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout financePanelLayout = new javax.swing.GroupLayout(financePanel);
        financePanel.setLayout(financePanelLayout);
        financePanelLayout.setHorizontalGroup(
            financePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financePanelLayout.createSequentialGroup()
                .addComponent(financeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(financeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        financePanelLayout.setVerticalGroup(
            financePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(financeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(financeImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        salesPanel.setBackground(new java.awt.Color(85, 65, 118));
        salesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salesPanelMousePressed(evt);
            }
        });

        salesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salesLabel.setForeground(new java.awt.Color(204, 204, 204));
        salesLabel.setText("Sales and Marketing");
        salesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesLabelMouseClicked(evt);
            }
        });

        salesImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Interstate_Truck_50px.png"))); // NOI18N
        salesImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        salesImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salesPanelLayout = new javax.swing.GroupLayout(salesPanel);
        salesPanel.setLayout(salesPanelLayout);
        salesPanelLayout.setHorizontalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addComponent(salesImage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        salesPanelLayout.setVerticalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hrPanel.setBackground(new java.awt.Color(85, 65, 118));
        hrPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hrPanelMousePressed(evt);
            }
        });

        hrLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hrLabel.setForeground(new java.awt.Color(204, 204, 204));
        hrLabel.setText("Human Resource");

        hrImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hrImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Return_50px.png"))); // NOI18N
        hrImage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout hrPanelLayout = new javax.swing.GroupLayout(hrPanel);
        hrPanel.setLayout(hrPanelLayout);
        hrPanelLayout.setHorizontalGroup(
            hrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrPanelLayout.createSequentialGroup()
                .addComponent(hrImage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        hrPanelLayout.setVerticalGroup(
            hrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hrImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Log out");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(financePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(17, 17, 17))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(stockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(productionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(financePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(salesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(hrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28))
        );

        salesDesktopPane.setBackground(new java.awt.Color(76, 77, 78));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FirstInterface.jpg"))); // NOI18N

        salesDesktopPane.setLayer(backgroundImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout salesDesktopPaneLayout = new javax.swing.GroupLayout(salesDesktopPane);
        salesDesktopPane.setLayout(salesDesktopPaneLayout);
        salesDesktopPaneLayout.setHorizontalGroup(
            salesDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesDesktopPaneLayout.createSequentialGroup()
                .addComponent(backgroundImage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        salesDesktopPaneLayout.setVerticalGroup(
            salesDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(salesDesktopPane))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesDesktopPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockPanelMousePressed
        setColor(stockPanel);
        resetColor(financePanel);
        resetColor(salesPanel);
        resetColor(hrPanel);
        resetColor(productionPanel);
        
        
    }//GEN-LAST:event_stockPanelMousePressed

    private void productionPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productionPanelMousePressed
        setColor(productionPanel);
        resetColor(financePanel);
        resetColor(salesPanel);
        resetColor(hrPanel);
        resetColor(stockPanel);
        
        
    }//GEN-LAST:event_productionPanelMousePressed

    private void financePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financePanelMousePressed
        setColor(financePanel);
        resetColor(stockPanel);
        resetColor(salesPanel);
        resetColor(hrPanel);
        resetColor(productionPanel);
        
        
    }//GEN-LAST:event_financePanelMousePressed

    private void salesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesPanelMousePressed
        setColor(salesPanel);
        resetColor(financePanel);
        resetColor(stockPanel);
        resetColor(hrPanel);
        resetColor(productionPanel);
        
        DeliveryMain dl = new DeliveryMain();
        salesDesktopPane.add(dl).setVisible(true);
    }//GEN-LAST:event_salesPanelMousePressed

    private void hrPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrPanelMousePressed
        setColor(hrPanel);
        resetColor(financePanel);
        resetColor(salesPanel);
        resetColor(stockPanel);
        resetColor(productionPanel);
        
        
    }//GEN-LAST:event_hrPanelMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        loginScreen ls = new loginScreen();
        ls.setExtendedState(loginScreen.MAXIMIZED_BOTH);
        ls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void salesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesLabelMouseClicked
        DeliveryMain dl = new DeliveryMain();
        salesDesktopPane.add(dl).setVisible(true);
        setColor(salesPanel);
        resetColor(financePanel);
        resetColor(hrPanel);
        resetColor(stockPanel);
        resetColor(productionPanel);
    }//GEN-LAST:event_salesLabelMouseClicked

    private void salesImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesImageMouseClicked
        DeliveryMain dl = new DeliveryMain();
        salesDesktopPane.add(dl).setVisible(true);
    }//GEN-LAST:event_salesImageMouseClicked

    public void setColor(JPanel panel)
    {
        panel.setBackground(new Color(54,33,89));
    }
    
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                
                
                int appWidth = (int)screenSize.getWidth() + 80;
                int appHeight = (int)screenSize.getHeight() -20;
                
                Theme mainApp = new Theme();
                mainApp.setPreferredSize(new java.awt.Dimension(appWidth, appHeight));
                mainApp.setExtendedState(mainApp.MAXIMIZED_BOTH);
                mainApp.setVisible(true);
                
                //mainApp.pack();
                
                //new Theme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel financeImage;
    private javax.swing.JLabel financeLabel;
    private javax.swing.JPanel financePanel;
    private javax.swing.JLabel hrImage;
    private javax.swing.JLabel hrLabel;
    private javax.swing.JPanel hrPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel productionImage;
    private javax.swing.JLabel productionLabel;
    private javax.swing.JPanel productionPanel;
    private javax.swing.JDesktopPane salesDesktopPane;
    private javax.swing.JLabel salesImage;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel stockImage;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JPanel stockPanel;
    // End of variables declaration//GEN-END:variables
}
